<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSAdDxuK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSAdDxuK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSAdDxuK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSAdDxuK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSAdDxuK\App_KernelDevDebugContainer([
    'container.build_hash' => 'SAdDxuK',
    'container.build_id' => '19c9acc1',
    'container.build_time' => 1727877719,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSAdDxuK');
