<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container54LEi6Q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container54LEi6Q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container54LEi6Q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container54LEi6Q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container54LEi6Q\App_KernelDevDebugContainer([
    'container.build_hash' => '54LEi6Q',
    'container.build_id' => 'c6b62b75',
    'container.build_time' => 1727880084,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container54LEi6Q');
